--- 
- 
  hosts: localhost
  name: "web server"
  tasks: 
    - 
      name: "install httpd php mysql"
      with_items: 
        - httpd
        - php
        - php-mysql
      yum: 
        name: "{{ item }}"
        state: present
    - 
      firewalld: 
        permanent: true
        port: 80/tcp
        state: enabled
        zone: public
      name: "add fw ports"
    - 
      command: "firewall-cmd --reload"
      name: "reload fw"
    - 
      command: "sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf"
      name: "index change"
    - 
      name: "start httpd"
      service: 
        name: httpd
        state: started
    - 
      command: "systemctl enable httpd"
      name: "sysctl en httpd"
    - 
      name: git
      yum: 
        name: git
        state: present
    - 
      command: "git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/"
      name: "get git code"

